# Generated by Django 4.2.3 on 2023-07-10 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PontoTuristico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('aprovado', models.BooleanField(verbose_name='Aprovado')),
            ],
            options={
                'verbose_name': 'PontoTuristico',
                'verbose_name_plural': 'PontosTuristicos',
            },
        ),
    ]
